### ISSUE TITLE
swipestart 与 tap 冲突了

### ISSUE THREAD

**Issue by ijfengg** [DMQ/mTouch#1]
场景：一个可拖动的按钮，期望效果点击该按钮出现子菜单，拖动按钮的时候将出现的子菜单隐藏。
我同时坚挺swipestart事件以及tap事件，当我单击按钮时同时响应了swipestart和tap

`mTouch('.mBtnTouch').on('tap',function (e)
 {
    console.log(e.mTouchEvent.type);
}).on('swipestart', function (event)
 {
    console.log(event.mTouchEvent.type)
};
`

**Comment by DMQ** [comment]
@ijfengg swipestart在touchstart的时候就会触发，tap点击的时候触发，所以这两个事件是会有重叠的。
但是你的场景不应该这样用，你应该监听swiping和tap事件
