### ISSUE TITLE
bug 一只

### ISSUE THREAD

**Issue by goldencolor** [DMQ/mTouch#6]
`
<ul class="lineList">
                    <li class="flex vCenter " :class="{'deleteItem':item.isDelete}" v-for="item in planListSelectIds" :data-id="item.id" v-touch:swipeleft="deleteItem">
                        <span style="font-size: .6rem;">{{item.name}}</span><em></em>
                        <a class="btn_touch_del" v-if="item.isDelete">删除</a></li>
                </ul>
`
在使用 touch:swipeleft绑定的时候 只有第一个循环的li才有效其他左滑都无效了。。

**Comment by goldencolor** [comment]
``` 
<ul class="lineList">
    <li class="flex vCenter " :class="{'deleteItem':item.isDelete}" v-for="item in planListSelectIds" :data-id="item.id" v-touch:swipeleft="deleteItem">
<span style="font-size: .6rem;">{{item.name}}</span><em></em>
<a class="btn_touch_del" v-if="item.isDelete">删除</a>
</li>
</ul>
```

**Comment by DMQ** [comment]
已修复bug，详见 https://github.com/DMQ/mTouch/commit/8283a1a392f61c2b9815f93467020c0aee9d6305
